<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="website" nsURI="https://tu-bs.de/isf/website" nsPrefix="website">
  <eClassifiers xsi:type="ecore:EClass" name="Website">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="-1"
        eType="#//Widget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Widget">
    <eOperations name="getRank" eType="#//Ranks"/>
    <eOperations name="getFile" eType="#//Files"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="square" lowerBound="1"
        eType="#//Square" eOpposite="#//Square/widget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextBox" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageBox" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ButtonBox" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SearchBox" eSuperTypes="#//Widget"/>
  <eClassifiers xsi:type="ecore:EClass" name="MenuitemBox" eSuperTypes="#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eOperations name="getSquare" eType="#//Square">
      <eParameters name="rank" eType="#//Ranks"/>
      <eParameters name="file" eType="#//Files"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="squares" lowerBound="64"
        upperBound="64" eType="#//Square" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widgets" upperBound="64"
        eType="#//Widget" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Square">
    <eOperations name="getOffsetX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="getOffsetY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="#//Files"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rank" eType="#//Ranks"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"
        defaultValueLiteral="none"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widget" eType="#//Widget"
        eOpposite="#//Widget/square"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Files">
    <eLiterals name="none"/>
    <eLiterals name="A" value="1"/>
    <eLiterals name="B" value="2"/>
    <eLiterals name="C" value="3"/>
    <eLiterals name="D" value="4"/>
    <eLiterals name="E" value="5"/>
    <eLiterals name="F" value="6"/>
    <eLiterals name="G" value="7"/>
    <eLiterals name="H" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Ranks">
    <eLiterals name="none"/>
    <eLiterals name="A" value="1"/>
    <eLiterals name="B" value="2"/>
    <eLiterals name="C" value="3"/>
    <eLiterals name="D" value="4"/>
    <eLiterals name="E" value="5"/>
    <eLiterals name="F" value="6"/>
    <eLiterals name="G" value="7"/>
    <eLiterals name="H" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="white"/>
    <eLiterals name="blue" value="1"/>
    <eLiterals name="none" value="2"/>
  </eClassifiers>
</ecore:EPackage>
